local infoview = require('lean.infoview')
local fixtures = require('tests.fixtures')

require('tests.helpers').setup{}
describe('infoview', function()
  describe('initial', function()
    it('opens',
    function(_)
      vim.api.nvim_command("edit " .. fixtures.lean3_project.some_existing_file)
      assert.kept_win()
      assert.kept_buf()
      infoview.get_current_infoview():open()
      assert.opened_infoview()
    end)

    it('remains open on BufEnter',
    function(_)
      vim.api.nvim_command("edit " .. fixtures.lean3_project.some_existing_file)
      assert.opened_infoview_kept()
    end)

    it('remains open on WinEnter',
    function(_)
      vim.api.nvim_command("split " .. fixtures.lean3_project.some_nested_existing_file)
      assert.created_buf()
      assert.created_win()
      assert.opened_infoview_kept()
      vim.api.nvim_command("close")
      assert.closed_win()
      assert.opened_infoview_kept()
    end)

    it('closes',
    function(_)
      vim.api.nvim_command('edit ' .. fixtures.lean3_project.some_existing_file)
      assert.opened_infoview_kept()
      infoview.get_current_infoview():close()
      assert.closed_infoview()
    end)

    it('remains closed on BufEnter',
    function(_)
      vim.api.nvim_command("edit " .. fixtures.lean3_project.some_nested_existing_file)
      assert.changed_buf()
      -- would be equivalent to just do assert.updated_infoviews() here, because this would
      -- correctly infer closed_infoview_kept; kept it (and others like it) for readability
      assert.closed_infoview_kept()
    end)

    it('remains closed on WinEnter',
    function(_)
      vim.api.nvim_command("split " .. fixtures.lean3_project.some_existing_file)
      assert.created_win()
      assert.changed_buf()
      assert.closed_infoview_kept()
      vim.api.nvim_command("close")
      assert.closed_win()
      assert.changed_buf()
      assert.closed_infoview_kept()
    end)

    it('manual quit succeeds and updates internal state',
    function(_)
      infoview.get_current_infoview():open()
      assert.opened_infoview()
      vim.api.nvim_command("wincmd l")
      assert.changed_buf()
      assert.changed_win()
      vim.api.nvim_command("quit")
      assert.closed_win()
      assert.closed_buf()
      assert.closed_infoview_none()
    end)

    it('manual close succeeds and updates internal state',
    function(_)
      infoview.get_current_infoview():open()
      assert.opened_infoview()
      vim.api.nvim_command("wincmd l")
      assert.changed_buf()
      assert.changed_win()
      vim.api.nvim_command("close")
      assert.closed_win()
      assert.closed_buf()
      assert.closed_infoview_none()
    end)
  end)

  describe('new tab', function()
    it('closes independently',
    function(_)
      infoview.get_current_infoview():open()
      assert.opened_infoview()
      vim.api.nvim_command("tabnew")
      assert.created_win()
      assert.created_buf()
      vim.api.nvim_command("edit " .. fixtures.lean_project.some_existing_file)
      assert.kept_buf()
      infoview.get_current_infoview():open()
      assert.opened_infoview()
      infoview.get_current_infoview():close()
      assert.closed_infoview()
      vim.api.nvim_command("tabprevious")
      assert.changed_buf()
      assert.changed_win()
      assert.opened_infoview_kept()
    end)

    it('opens independently',
    function(_)
      infoview.get_current_infoview():close()
      assert.closed_infoview()
      vim.api.nvim_command("tabnext")
      assert.changed_buf()
      assert.changed_win()
      infoview.get_current_infoview():open()
      assert.opened_infoview()
      vim.api.nvim_command("tabprevious")
      assert.changed_buf()
      assert.changed_win()
      assert.closed_infoview_kept()
      vim.api.nvim_command("tabnext")
      assert.changed_buf()
      assert.changed_win()
      assert.opened_infoview_kept()
    end)

    it('closes when only window',
    function(_)
      vim.api.nvim_command("close")
      assert.changed_buf()
      assert.closed_win()
      assert.opened_infoview_kept()
      local tabpage = vim.api.nvim_win_get_tabpage(0)
      infoview.get_current_infoview():close()
      assert.closed_buf()
      assert.closed_win()
      assert.closed_infoview_none({tabpage})
    end)
  end)
end)
