name: Abbreviations

on:
  schedule:
    - cron: "44 2 * * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}

jobs:
  sync:
    name: Sync abbreviations
    runs-on: ubuntu-latest

    permissions:
      contents: write # for committing updated abbreviation definitions

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: true
      - name: Download VSCode abbreviations
        run: |
          gh api -H 'Accept: application/vnd.github.raw' '/repos/leanprover/vscode-lean4/contents/lean4-unicode-input/src/abbreviations.json' >vscode-lean/abbreviations.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "Sync abbreviations with the VSCode definitions"
            git push
          fi
