name: Regenerate Documentation

on:
  push:
    branches-ignore:
      - "benchmark*"
      - "wip*"
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: Regenerate vimdocs
    runs-on: ubuntu-latest

    permissions:
      contents: write # for committing regenerated vimdocs

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: true

      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3
      - name: Install Neovim
        uses: rhysd/action-setup-vim@febef33995d6649302e9d88dda81e071b68f16a7
        with:
          neovim: true
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659
      - name: Install vimcats
        run: cargo install vimcats --features=cli --force

      - name: Generate docs
        run: just docs

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add doc/*.txt
          if ! git diff --staged --quiet; then
            git commit -m "Regenerate vimdocs"
            git push
          fi
