name: Regenerate Documentation

on:
  push:
    branches-ignore:
      - "benchmark*"
      - "wip*"
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true

      - uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b
      - name: Install Neovim
        uses: rhysd/action-setup-vim@19e3dd31a84dbc2c5445d65e9b363f616cab96c1
        with:
          neovim: true
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606
      - name: Install vimcats
        run: cargo install vimcats --features=cli --force

      - name: Generate docs
        run: just docs

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9
        with:
          branch: ${{ github.head_ref }}
          commit_message: "Regenerate vimdocs"
          file_pattern: doc/*.txt
