name: Regenerate Documentation

on:
  push:
    branches-ignore:
      - "benchmark*"
      - "wip*"
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true

      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3
      - name: Install Neovim
        uses: rhysd/action-setup-vim@febef33995d6649302e9d88dda81e071b68f16a7
        with:
          neovim: true
      - uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7
      - name: Install vimcats
        run: cargo install vimcats --features=cli --force

      - name: Generate docs
        run: just docs

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9
        with:
          branch: ${{ github.head_ref }}
          commit_message: "Regenerate vimdocs"
          file_pattern: doc/*.txt
