name: "Release"
on:
  push:
    tags:
      - "v*.*"

jobs:
  luarocks-release:
    name: "LuaRocks Release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
